services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    image: blueprint-prod:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/opt/project/db.sqlite3
