services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    image: blueprint-prod:latest
    restart: unless-stopped
    environment:
      - ENV_FOR_DYNACONF=production
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/opt/project/db.sqlite3
