services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        APP_UID: 1000
        APP_GID: 1001
    environment:
      - ENV_FOR_DYNACONF=development
    volumes:
      - ./project:/opt/project/project
      - ./src:/opt/project/src
      - ./db.sqlite3:/opt/project/db.sqlite3
