services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_UID: 1000
        APP_GID: 1001
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project:/opt/project/project
      - ./src:/opt/project/src
      - ./db.sqlite3:/opt/project/db.sqlite3
